// Generated by CoffeeScript 1.6.1
(function() {
  var MetApi;

  module.exports = MetApi = (function() {

    function MetApi(apiKey) {
      if (apiKey && typeof apiKey === "string") {
        this.apiKey = apiKey;
      } else {
        throw new Error("apiKey is a required parameter");
      }
    }

    MetApi.prototype._getLocationId = function(location) {};

    return MetApi;

  })();

}).call(this);
